#!/usr/bin/env php// {{-- Copyright (c) 2025 Dilshan De Silva
//     This software and associated documentation files DoubleClick are the exclusive property of Dilshan De Silva. 
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
